require('./test-helper');

require('./confirmation');
require('./images');
require('./layout');
require('./notify');
require('./pagination');
require('./review');
require('./items-list-view');
require('./thumbnail');
require('./items-toolbar');
require('./items');
require('./scanning');
require('./folders');
require('./reports');
require('./storage');
require('./support');
require('./users');
require('./widgets');
