require('./bulk-selection_test');
require('./confirmation-input_test');
require('./currency-input_test');
require('./draggable-item-directive_test');
require('./is-selected_test');
require('./file-input_test');
require('./form-group-test');
require('./is-selected_test');
require('./table-data-field_test');
